In [1]:
import pandas as pd
import datetime
import math
import numpy

Burpple = pd.read_excel(r"(TP) From2016_Sentimental_Burpple.xlsx")
Dates = Dates = Burpple['Date'].tolist()

condition = ''
Form = []
why = []
day = ''
mon = ''
year = ''
monyear = ''
Date = ''

for i in Dates:
    
    condition = i.split()[2]
    
    if condition == "ago":
        day = i.split()[0]
        monyear = "May 2018"
        year = "2018"
        Date = day + " " + monyear
        Form.append(Date)
        why.append(year)
        
    elif condition == "at":
        mon = i.split()[0]
        day = i.split()[1]
        year = "2018"
        Date = day+" "+ mon + " 2018"
        Form.append(Date)
        why.append(year)
        
    else:
        day = i.split()[1]
        day = day.replace(',','')
        mon = i.split()[0]
        year = i.split()[2]
        Date = day + " " + mon + " " + year
        Form.append(Date)
        why.append(year)
        
 
              
num = len(Burpple)
NewDate = []
Quart = []
Q = 0
yy = ''
strdate = ''

for i in range (0, num):
    Date = datetime.datetime.strptime(Form[i], '%d %b %Y').strftime('%d/%m/%Y')
    Date = datetime.datetime.strptime(Date,'%d/%m/%Y')
    
    NewDate.append(Date)

    Q=math.ceil(Date.month/3.)
    #print(Q)
    Quart.append(Q)
    
    #strdate = str(Date)
    #yy = Date.Year
    #bpyear.append(yy)
    
       
FormatDate = pd.Series(NewDate)
Burpple['Formated_Date'] = FormatDate.values

Quarter = pd.Series(Quart)
Burpple['Quarter'] = Quarter.values

Year = pd.Series(why)
Burpple['Year'] = Year.values

ex = pd.ExcelWriter('(TP) Quarters.xlsx', options={'encoding':'utf-8'})
Burpple.to_excel(ex, 'Data', index=False)

#AllNames = Burpple.groupby('Café_Names', sort=False, as_index=False).Title.count().reset_index(drop=True)
#NoR = AllNames['Title'].tolist()


### sorting the data by Years

y2016 = pd.DataFrame()
y2017 = pd.DataFrame()
y2018 = pd.DataFrame()
No2016 = []
No2017 = []
No2018 = []

for i in range (0, num):
    if why[i] == '2016':
        No2016.append(i)
    if why[i] == '2017':
        No2017.append(i)
    if why[i] == '2018':
        No2018.append(i)
    
y2016 = pd.DataFrame(Burpple.iloc[No2016])
y2017 = pd.DataFrame(Burpple.iloc[No2017])
y2018 = pd.DataFrame(Burpple.iloc[No2018])


y2016 = y2016.reset_index(drop = True)
y2017 = y2017.reset_index(drop = True)
y2018 = y2018.reset_index(drop = True)

#next decide how you want to split the data.
#seperate each year into diff files? How about the average sentiment?

###  Resturant  Avg_sentiment Quarter_1 Quarter_2 Quarter_3 Quarter_4
###  xxx        0.01          0.2       0.021     0.45      0.46

In [2]:
### for the year 2017

AllNames2017 = y2017.groupby('Café_Names', sort=False, as_index=False).Title.count().reset_index(drop=True)
NoR2017 = AllNames2017['Title'].tolist()

Quarter = y2017['Quarter'].tolist()

num = len(y2017)
No1 = []
No2 =[]
No3 =[]
No4 =[]

for i in range(0, num):
    if Quarter[i] == 1:
        No1.append(i)
    if Quarter[i] == 2:
        No2.append(i)
    if Quarter[i] == 3:
        No3.append(i)
    if Quarter[i] == 4:
        No4.append(i)
        
#creating databases based on the quarter

q1 = pd.DataFrame(y2017.iloc[No1])
q2 = pd.DataFrame(y2017.iloc[No2])
q3 = pd.DataFrame(y2017.iloc[No3])
q4 = pd.DataFrame(y2017.iloc[No4])

# Quarter 1

AllNames1 = q1.groupby('Café_Names', sort=False, as_index=False).Title.count().reset_index(drop=True)
NoR1 = AllNames1['Title'].tolist()

Q1YN =[]
names = AllNames2017['Café_Names'].tolist()
names1 = AllNames1['Café_Names'].tolist()

for i in names:
    if i in names1:
        Q1YN.append("Yes")
    else:
        Q1YN.append("")

polarity = q1['polarity'].tolist()        
num = len(NoR2017)
pos = 0
poss = 0
counta = 0
total = float(0)
average = float(0)
avg1 = []

for i in range (0, num):
    if Q1YN[i] == "Yes":
        pos = pos + NoR1[counta]
        total = 0
        average = 0
        for x in range(poss, pos):
            total = total + polarity[x]
        average = total / NoR1[counta]
        avg1.append(average)
        poss = pos
        counta = counta + 1
    else:
        avg1.append(0)
        
Avg_Q1 = pd.Series(avg1)       
AllNames2017['Q1_Average_Polarity'] = Avg_Q1.values

In [3]:
# Quarter 2

AllNames2 = q2.groupby('Café_Names', sort=False, as_index=False).Title.count().reset_index(drop=True)
NoR2 = AllNames2['Title'].tolist()

Q2YN =[]
names = AllNames2017['Café_Names'].tolist()
names2 = AllNames2['Café_Names'].tolist()

for i in names:
    if i in names2:
        Q2YN.append("Yes")
    else:
        Q2YN.append("")

polarity = q2['polarity'].tolist()        
num = len(NoR2017)
pos = 0
poss = 0
counta = 0
total = float(0)
average = float(0)
avg2 = []

for i in range (0, num):
    if Q2YN[i] == "Yes":
        pos = pos + NoR2[counta]
        total = 0
        average = 0
        for x in range(poss, pos):
            total = total + polarity[x]
        average = total / NoR2[counta]
        avg2.append(average)
        poss = pos
        counta = counta + 1
    else:
        avg2.append(0)
        
Avg_Q2 = pd.Series(avg2)       
AllNames2017['Q2_Average_Polarity'] = Avg_Q2.values

In [4]:
# Quarter 3

AllNames3 = q3.groupby('Café_Names', sort=False, as_index=False).Title.count().reset_index(drop=True)
NoR3 = AllNames3['Title'].tolist()

Q3YN =[]
names = AllNames2017['Café_Names'].tolist()
names3 = AllNames3['Café_Names'].tolist()

for i in names:
    if i in names3:
        Q3YN.append("Yes")
    else:
        Q3YN.append("")

polarity = q3['polarity'].tolist()        
num = len(NoR2017)
pos = 0
poss = 0
counta = 0
total = float(0)
average = float(0)
avg3 = []

for i in range (0, num):
    if Q3YN[i] == "Yes":
        pos = pos + NoR3[counta]
        total = 0
        average = 0
        for x in range(poss, pos):
            total = total + polarity[x]
        average = total / NoR3[counta]
        avg3.append(average)
        poss = pos
        counta = counta + 1
    else:
        avg3.append(0)
        
Avg_Q3 = pd.Series(avg3)       
AllNames2017['Q3_Average_Polarity'] = Avg_Q3.values

In [5]:
# Quarter 4

AllNames4 = q4.groupby('Café_Names', sort=False, as_index=False).Title.count().reset_index(drop=True)
NoR4 = AllNames4['Title'].tolist()

Q4YN =[]
names = AllNames2017['Café_Names'].tolist()
names4 = AllNames4['Café_Names'].tolist()

for i in names:
    if i in names4:
        Q4YN.append("Yes")
    else:
        Q4YN.append("")

polarity = q4['polarity'].tolist()        
num = len(NoR2017)
pos = 0
poss = 0
counta = 0
total = float(0)
average = float(0)
avg4 = []

for i in range (0, num):
    if Q4YN[i] == "Yes":
        pos = pos + NoR4[counta]
        total = 0
        average = 0
        for x in range(poss, pos):
            total = total + polarity[x]
        average = total / NoR4[counta]
        avg4.append(average)
        poss = pos
        counta = counta + 1
    else:
        avg4.append(0)
        
Avg_Q4 = pd.Series(avg4)       
AllNames2017['Q4_Average_Polarity'] = Avg_Q4.values

In [8]:
AllNames2017.columns = ['Café_Names', 'Count','Q1_Average_Polarity', 'Q2_Average_Polarity','Q3_Average_Polarity', 'Q4_Average_Polarity']

ex = pd.ExcelWriter('(TP) 2017_Average Sentiment by Quarter.xlsx', options={'encoding':'utf-8'})
AllNames2017.to_excel(ex, 'Data', index=False)

In [7]:
AllNames2017

,Café_Names,Count,Q1_Average_Polarity,Q2_Average_Polarity,Q3_Average_Polarity,Q4_Average_Polarity
0,The Populus Coffee & Food Co.,73,0.288798,0.183899,0.135576,0.181553
1,Xiao Ya Tou,125,0.186158,0.171002,0.209191,0.118381
2,The Lokal,84,0.244979,0.280121,0.248919,0.162905
3,Chong Wen Ge Cafe 崇文阁,14,0.285364,0.163845,0.286667,0.357143
4,Common Man Stan,11,0.000000,0.000000,0.000000,0.170596
5,Lunar Coffee Brewers,54,0.000000,0.131679,0.198373,0.070146
6,Guac & Go,8,0.084735,0.260498,0.120893,0.125893
7,1KS,16,0.000000,0.000000,0.171959,0.123571
8,Well Dressed Salad Bar & Cafe,14,0.283945,0.000000,0.150894,0.275455
9,Group Therapy (Duxton),32,0.485494,0.220833,0.180222,0.163770
10,VENUE by Sebastian,56,0.000000,0.261574,0.204723,0.082143
11,NINJA BOWL,91,0.237898,0.162813,0.180372,0.152344
12,Mavrx Coffee Apothecary,2,0.047619,0.000000,0.000000,0.000000
13,My Awesome Cafe,9,0.107245,0.268095,0.000000,0.000000
14,Café & Bar Gavroche,4,0.000000,0.115278,0.500000,0.000000
15,JAPAN RAIL CAFE,58,0.140619,0.058916,0.516111,0.312081
16,Dapper Coffee,23,0.197378,0.126349,0.218856,0.000000
17,Nylon Coffee Roasters,18,0.225000,0.589583,0.175778,0.190631
18,5 The Moments,57,0.196808,0.456250,0.231710,0.073810
19,Eight Cafe & Bar,11,0.170075,0.369333,0.164556,0.000000
20,Pantler,27,0.084742,0.057361,0.114982,0.198983
21,Luxe,5,0.000000,0.248778,0.000000,0.043229
22,Monument Lifestyle,20,0.260995,0.168816,0.102569,0.150000
23,PS.Cafe (Ann Siang Hill),18,0.069841,0.125000,0.214500,0.091865
24,Orchid Cafe (Orchid Hotel),5,0.000000,0.258333,-0.005833,0.287094
25,Café 2000 (M Hotel),4,0.000000,0.004356,0.000000,0.134990
26,Drury Lane (Tanjong Pagar),29,0.080403,0.245139,0.132778,0.146158
27,Hattendo Cafe,85,0.197889,0.255275,0.341631,0.177077
28,Royz et Vous (Telok Ayer),11,0.149167,0.000000,0.359091,-0.200000
29,Coffee Break (Amoy Street Food Centre),17,-0.030330,0.087500,0.228058,0.160052
...,...,...,...,...,...,...
36,Epiphyte,23,0.178948,0.122336,0.195790,0.058333
37,Omotesando Koffee,20,0.000000,0.000000,0.272002,0.224980
38,Pickleville,7,0.000000,0.000000,0.000000,0.095574
39,Alchemist (International Plaza),5,0.700000,0.050000,0.016667,0.000000
40,Huggs Cafe (Cecil Street),2,0.000000,0.000000,0.000000,-0.025000
41,Mellower Coffee (Tanjong Pagar),10,0.198425,0.000000,0.274603,0.110216
42,Merchants Wine Cellar & Store (Duxton Hill),2,0.000000,0.000000,0.500000,0.000000
43,Ah Seng (Hai Nam) Coffee (Amoy Street Food Cen...,3,0.209314,0.000000,0.235714,0.180000
44,Chatuchak Thai Tea,31,0.157222,0.037963,0.000000,0.157351
45,The Autobus,7,0.000000,0.000000,0.165978,0.290714
46,Henri Charpentier (Tanjong Pagar Centre),17,0.163934,0.175763,0.203968,0.700000
47,HashTag88 Cafe & Bar,2,0.000000,0.000000,0.461905,0.000000
48,Tom N Toms Coffee,5,0.000000,0.116032,0.000000,0.350000
49,6oz Espresso Bar (Tokio Marine Centre),4,0.273810,0.150000,0.000000,0.000000
50,Cedele Bakery Cafe (Robinson Road),2,0.000000,0.000000,0.241667,0.700000
51,The Coffee Bean & Tea Leaf (International Plaza),1,0.000000,0.000000,0.000000,0.000000
52,Kanoom - Little Thai Cafe,1,0.500000,0.000000,0.000000,0.000000
53,Joe & The Juice (Tanjong Pagar Centre),3,0.266667,0.000000,0.166667,-0.010204
54,Rocky Master (Mapletree Anson),1,0.000000,0.000000,0.000000,0.000000
55,BLUEMIST Cafe,3,0.000000,0.000000,0.166667,0.000000
56,Kosnica,6,0.177778,0.000000,0.000000,0.118182
57,Trung Nguyen Coffee (International Plaza),2,0.000000,0.616667,1.000000,0.000000
58,Ash & Char,18,0.118772,0.700000,0.156657,0.400000
59,Rookery (Capital Tower),4,0.000000,0.000000,0.000000,0.302083
60,Patisserie G (Downtown Gallery),2,0.000000,0.000000,0.052083,0.000000
61,The Providore (Downtown Gallery),13,0.000000,0.000000,0.361245,0.120000
62,The New Harbour Café & Bar,3,0.000000,0.000000,0.151009,0.000000
63,Socks & Pans,1,0.500000,0.000000,0.000000,0.000000
64,Loloku,19,0.172446,0.039210,0.323333,0.000000
65,Starbucks (Capital Tower),1,0.000000,0.000000,0.125000,0.000000

In [127]:
y2017[y2017['Café_Names'].str.contains("Costa Coffee")]

,Café_Names,Date,Title,Review,Cleaned_Reviews,polarity,subjectivity,Formated_Date,Quarter,Year
1052,Costa Coffee (Sofitel So Singapore),"Nov 27, 2016",Enjoying a Flat White and toasted Turkey Ham &...,#burpple,NaN,0.0,0.0,2016-11-27,4,2016

In [87]:
AllNames1

,Café_Names,Title,Q1_Average_Polarity
0,The Populus Coffee & Food Co.,70,0.226939
1,The Lokal,40,0.000000
2,Guac & Go,1,0.000000
3,Well Dressed Salad Bar & Cafe,1,0.192901
4,Group Therapy (Duxton),3,0.000000
5,Mavrx Coffee Apothecary,3,0.000000
6,My Awesome Cafe,2,0.000000
7,Dapper Coffee,9,0.350000
8,Nylon Coffee Roasters,4,0.000000
9,5 The Moments,1,0.530000
10,Eight Cafe & Bar,1,0.199405
11,Pantler,9,0.000000
12,Luxe,6,0.000000
13,PS.Cafe (Ann Siang Hill),2,0.276389
14,Orchid Cafe (Orchid Hotel),1,0.000000
15,Good Morning Nanyang Cafe 早安南洋 (Maxwell Chambers),1,0.000000
16,Drury Lane (Tanjong Pagar),6,0.000000
17,Royz et Vous (Telok Ayer),2,0.204902
18,Coffee Break (Amoy Street Food Centre),1,0.087500
19,The White Rocket,2,0.142857
20,Bingki Korean Dessert Cafe,5,0.125000
21,Merchants Wine Cellar & Store (Duxton Hill),1,0.177280
22,Tom N Toms Coffee,2,0.120939
23,Joe & Dough (Capital Tower),7,0.000000
24,6oz Espresso Bar (Tokio Marine Centre),1,0.441667
25,Kanoom - Little Thai Cafe,1,0.000000
26,Urban Fairways,7,0.000000
27,Trung Nguyen Coffee (International Plaza),3,0.000000
28,Coffee & Toast (Tanjong Pagar Xchange),1,0.000000
29,The New Harbour Café & Bar,1,0.037500
30,Socks & Pans,2,0.344365
31,Starbucks (Capital Tower),1,0.000000