In [1]:
import nltk
from nltk.collocations import *
import pandas as pd

In [2]:
with open('data.txt', 'rb') as f:
    data = f.read()

In [3]:
data = str(data).split(" ")

In [4]:
bigram_measures = nltk.collocations.BigramAssocMeasures()
finder = BigramCollocationFinder.from_words(data)
finder.apply_freq_filter(15) 
finder.nbest(bigram_measures.raw_freq, 15)

[('ice', 'cream'),
 ('salted', 'egg'),
 ('french', 'toast'),
 ('scrambled', 'eggs'),
 ('earl', 'grey'),
 ('tanjong', 'pagar'),
 ('onsen', 'egg'),
 ('flat', 'white'),
 ('pulled', 'pork'),
 ('vanilla', 'ice'),
 ('road', 'singapore'),
 ('truffle', 'fries'),
 ('black', 'sesame'),
 ('sweet', 'potato'),
 ('raffles', 'place')]

In [5]:
bigram_measures = nltk.collocations.BigramAssocMeasures()
finder = BigramCollocationFinder.from_words(data)
finder.apply_freq_filter(15) 
df=finder.nbest(bigram_measures.raw_freq, 15)

num = len(df)
tempword = ''
wtempword = ''
whole = []

for i in range (0, num):
    tempnum = len(df[i])
    for x in range (0, tempnum):
        tempword = df[i][x]
        wtempword = wtempword +  " " + tempword
    whole.append(wtempword.lstrip())
    tempword = ""
    wtempword = ""
    
Resturants =  pd.read_excel(r"From2016_Sentimental_Burpple.xlsx")
Reviews = Resturants['Cleaned_Reviews'].tolist()
polarity = Resturants['polarity'].tolist()

num = len(whole)
num1 = len(Reviews)
count = 0
countlist = []
targetword = ''
targetreview = ''
average = float(0)
total = float(0)
averagelist = []

for i in range (0, num):
    targetword = whole[i]
    for x in range( 0, num1):
        targetreview = str(Reviews[x])
        if targetreview.find(targetword) >= 0:
            count = count + 1
            total = total + polarity[x]
        targetreview = ""
    average = total/count
    averagelist.append(average)
    countlist.append(count)
    count = 0
    average = 0
    total = 0
    targetword = ""
    
Freq = pd.DataFrame()

se = pd.Series(whole)
Freq['Word'] = se

se = pd.Series(countlist)
Freq['Count'] = se

se = pd.Series(averagelist)
Freq['Average_Polarity'] = se

Freq

              Word  Count  Average_Polarity
0        ice cream    318          0.214892
1       salted egg     92          0.135809
2     french toast    112          0.176912
3   scrambled eggs     92          0.214287
4        earl grey     73          0.130763
5    tanjong pagar     87          0.174975
6        onsen egg     84          0.228758
7       flat white     74          0.132035
8      pulled pork     58          0.180603
9      vanilla ice     69          0.239745
10  road singapore     72          0.139507
11   truffle fries     59          0.244113
12    black sesame     45          0.129306
13    sweet potato     60          0.188713
14   raffles place     47          0.159880

In [6]:
trigram_measures = nltk.collocations.TrigramAssocMeasures()
finder = TrigramCollocationFinder.from_words(data)
finder.apply_freq_filter(15) 
finder.nbest(trigram_measures.raw_freq, 15)

[('vanilla', 'ice', 'cream'),
 ('salted', 'egg', 'yolk'),
 ('sticky', 'date', 'pudding'),
 ('xiao', 'ya', 'tou'),
 ('per', 'person', 'photo'),
 ('angel', 'hair', 'pasta'),
 ('thai', 'milk', 'tea'),
 ('braised', 'beef', 'cheek'),
 ('cafehoppingsg', 'sgcafefood', 'sgfoodie'),
 ('igsg', 'cafehoppingsg', 'sgcafefood'),
 ('person', 'photo', 'burppler'),
 ('6', 'duxton', 'hill'),
 ('duxton', 'road', 'singapore'),
 ('duxton', 'hill', 'singapore'),
 ('15', 'duxton', 'road')]

In [7]:
trigram_measures = nltk.collocations.TrigramAssocMeasures()
finder = TrigramCollocationFinder.from_words(data)
finder.apply_freq_filter(15) 
df = finder.nbest(trigram_measures.raw_freq, 15)  


num = len(df)
tempword = ''
wtempword = ''
whole = []

for i in range (0, num):
    tempnum = len(df[i])
    for x in range (0, tempnum):
        tempword = df[i][x]
        wtempword = wtempword +  " " + tempword
    whole.append(wtempword.lstrip())
    tempword = ""
    wtempword = ""
    
Resturants =  pd.read_excel(r"From2016_Sentimental_Burpple.xlsx")
Reviews = Resturants['Cleaned_Reviews'].tolist()
polarity = Resturants['polarity'].tolist()

num = len(whole)
num1 = len(Reviews)
count = 0
countlist = []
targetword = ''
targetreview = ''
average = float(0)
total = float(0)
averagelist = []

for i in range (0, num):
    targetword = whole[i]
    for x in range( 0, num1):
        targetreview = str(Reviews[x])
        if targetreview.find(targetword) >= 0:
            count = count + 1
            total = total + polarity[x]
        targetreview = ""
    average = total/count
    averagelist.append(average)
    countlist.append(count)
    count = 0
    average = 0
    total = 0
    targetword = ""
    
Freq1 = pd.DataFrame()

se = pd.Series(whole)
Freq1['Word'] = se

se = pd.Series(countlist)
Freq1['Count'] = se

se = pd.Series(averagelist)
Freq1['Average_Polarity'] = se

Freq1

                                 Word  Count  Average_Polarity
0                   vanilla ice cream     68          0.236849
1                     salted egg yolk     24          0.104435
2                 sticky date pudding     26          0.293032
3                         xiao ya tou     32          0.203905
4                    per person photo     33          0.206084
5                    angel hair pasta     30          0.256614
6                       thai milk tea     24          0.149468
7                  braised beef cheek     31          0.180657
8   cafehoppingsg sgcafefood sgfoodie     26          0.198199
9       igsg cafehoppingsg sgcafefood     25          0.206127
10              person photo burppler     25          0.222012
11                      6 duxton hill     24          0.126393
12              duxton road singapore     24          0.145213
13              duxton hill singapore     23          0.121452
14                     15 duxton road     22          0.149094

In [8]:
finder = BigramCollocationFinder.from_words(data)
scored = finder.score_ngrams(bigram_measures.raw_freq)
set(bigram for bigram, score in scored) 
sorted(finder.nbest(bigram_measures.raw_freq,20))

[('black', 'sesame'),
 ('cold', 'brew'),
 ('earl', 'grey'),
 ('flat', 'white'),
 ('french', 'toast'),
 ('fried', 'chicken'),
 ('ice', 'cream'),
 ('onsen', 'egg'),
 ('poached', 'eggs'),
 ('pork', 'belly'),
 ('pulled', 'pork'),
 ('raffles', 'place'),
 ('road', 'singapore'),
 ('salted', 'egg'),
 ('scrambled', 'eggs'),
 ('smoked', 'salmon'),
 ('sweet', 'potato'),
 ('tanjong', 'pagar'),
 ('truffle', 'fries'),
 ('vanilla', 'ice')]

In [9]:
finder = BigramCollocationFinder.from_words(data)
scored = finder.score_ngrams(bigram_measures.raw_freq)
set(bigram for bigram, score in scored) 
df = sorted(finder.nbest(bigram_measures.raw_freq,20))


num = len(df)
tempword = ''
wtempword = ''
whole = []

for i in range (0, num):
    tempnum = len(df[i])
    for x in range (0, tempnum):
        tempword = df[i][x]
        wtempword = wtempword +  " " + tempword
    whole.append(wtempword.lstrip())
    tempword = ""
    wtempword = ""
    
Resturants =  pd.read_excel(r"From2016_Sentimental_Burpple.xlsx")
Reviews = Resturants['Cleaned_Reviews'].tolist()
polarity = Resturants['polarity'].tolist()

num = len(whole)
num1 = len(Reviews)
count = 0
countlist = []
targetword = ''
targetreview = ''
average = float(0)
total = float(0)
averagelist = []

for i in range (0, num):
    targetword = whole[i]
    for x in range( 0, num1):
        targetreview = str(Reviews[x])
        if targetreview.find(targetword) >= 0:
            count = count + 1
            total = total + polarity[x]
        targetreview = ""
    average = total/count
    averagelist.append(average)
    countlist.append(count)
    count = 0
    average = 0
    total = 0
    targetword = ""
    
Freq2 = pd.DataFrame()

se = pd.Series(whole)
Freq2['Word'] = se

se = pd.Series(countlist)
Freq2['Count'] = se

se = pd.Series(averagelist)
Freq2['Average_Polarity'] = se

Freq2

              Word  Count  Average_Polarity
0     black sesame     45          0.129306
1        cold brew     45          0.011630
2        earl grey     73          0.130763
3       flat white     74          0.132035
4     french toast    112          0.176912
5    fried chicken     44         -0.034049
6        ice cream    318          0.214892
7        onsen egg     84          0.228758
8     poached eggs     52          0.219845
9       pork belly     46          0.129277
10     pulled pork     58          0.180603
11   raffles place     47          0.159880
12  road singapore     72          0.139507
13      salted egg     92          0.135809
14  scrambled eggs     92          0.214287
15   smoked salmon     46          0.213131
16    sweet potato     60          0.188713
17   tanjong pagar     87          0.174975
18   truffle fries     59          0.244113
19     vanilla ice     69          0.239745

In [10]:
finder = TrigramCollocationFinder.from_words(data)
scored = finder.score_ngrams(trigram_measures.raw_freq)
set(trigram for trigram, score in scored) 
sorted(finder.nbest(trigram_measures.raw_freq,20))

[('15', 'duxton', 'road'),
 ('6', 'duxton', 'hill'),
 ('angel', 'hair', 'pasta'),
 ('braised', 'beef', 'cheek'),
 ('cafehoppingsg', 'sgcafefood', 'sgfoodie'),
 ('duxton', 'hill', 'singapore'),
 ('duxton', 'road', 'singapore'),
 ('hill', 'singapore', '089592\\r\\n'),
 ('http', 'danielfooddiary', 'com'),
 ('igsg', 'cafehoppingsg', 'sgcafefood'),
 ('neil', 'road', 'singapore'),
 ('per', 'person', 'photo'),
 ('person', 'photo', 'burppler'),
 ('salted', 'egg', 'yolk'),
 ('sgcafefood', 'sgfoodie', 'singaporeeats'),
 ('sticky', 'date', 'pudding'),
 ('thai', 'milk', 'tea'),
 ('vanilla', 'ice', 'cream'),
 ('www', 'misstamchiak', 'com'),
 ('xiao', 'ya', 'tou')]

In [11]:
finder = TrigramCollocationFinder.from_words(data)
scored = finder.score_ngrams(trigram_measures.raw_freq)
set(trigram for trigram, score in scored) 
df = sorted(finder.nbest(trigram_measures.raw_freq,20))


num = len(df)
tempword = ''
wtempword = ''
whole = []

for i in range (0, num):
    tempnum = len(df[i])
    for x in range (0, tempnum):
        tempword = df[i][x]
        wtempword = wtempword +  " " + tempword
    whole.append(wtempword.lstrip())
    tempword = ""
    wtempword = ""
    
Resturants =  pd.read_excel(r"From2016_Sentimental_Burpple.xlsx")
Reviews = Resturants['Cleaned_Reviews'].tolist()
polarity = Resturants['polarity'].tolist()

num = len(whole)
num1 = len(Reviews)
count = 0
countlist = []
targetword = ''
targetreview = ''
average = float(0)
total = float(0)
averagelist = []

for i in range (0, num):
    targetword = whole[i]
    for x in range( 0, num1):
        targetreview = str(Reviews[x])
        if targetreview.find(targetword) >= 0:
            count = count + 1
            total = total + polarity[x]
        targetreview = ""
        
    if count == 0 or total == 0:
        average = 0
    else:
        average = total/count
    
    averagelist.append(average)
    countlist.append(count)
    count = 0
    average = 0
    total = 0
    targetword = ""
    
Freq3 = pd.DataFrame()

se = pd.Series(whole)
Freq3['Word'] = se

se = pd.Series(countlist)
Freq3['Count'] = se

se = pd.Series(averagelist)
Freq3['Average_Polarity'] = se

Freq3

                                 Word  Count  Average_Polarity
0                      15 duxton road     22          0.149094
1                       6 duxton hill     24          0.126393
2                    angel hair pasta     30          0.256614
3                  braised beef cheek     31          0.180657
4   cafehoppingsg sgcafefood sgfoodie     26          0.198199
5               duxton hill singapore     23          0.121452
6               duxton road singapore     24          0.145213
7           hill singapore 089592\r\n      0          0.000000
8            http danielfooddiary com     20          0.132154
9       igsg cafehoppingsg sgcafefood     25          0.206127
10                neil road singapore     23          0.120581
11                   per person photo     33          0.206084
12              person photo burppler     25          0.222012
13                    salted egg yolk     24          0.104435
14  sgcafefood sgfoodie singaporeeats     26          0.198199
15                sticky date pudding     26          0.293032
16                      thai milk tea     24          0.149468
17                  vanilla ice cream     68          0.236849
18               www misstamchiak com     20          0.006757
19                        xiao ya tou     32          0.203905

In [12]:
everything = Freq.append(Freq1)
everything = everything.append(Freq2)
everything = everything.append(Freq3)

everything = everything.sort_values(['Average_Polarity'], ascending=[0])

everything

                                 Word  Count  Average_Polarity
15                sticky date pudding     26          0.293032
2                 sticky date pudding     26          0.293032
5                    angel hair pasta     30          0.256614
2                    angel hair pasta     30          0.256614
18                      truffle fries     59          0.244113
11                      truffle fries     59          0.244113
19                        vanilla ice     69          0.239745
9                         vanilla ice     69          0.239745
17                  vanilla ice cream     68          0.236849
0                   vanilla ice cream     68          0.236849
7                           onsen egg     84          0.228758
6                           onsen egg     84          0.228758
10              person photo burppler     25          0.222012
12              person photo burppler     25          0.222012
8                        poached eggs     52          0.219845
6                           ice cream    318          0.214892
0                           ice cream    318          0.214892
14                     scrambled eggs     92          0.214287
3                      scrambled eggs     92          0.214287
15                      smoked salmon     46          0.213131
9       igsg cafehoppingsg sgcafefood     25          0.206127
9       igsg cafehoppingsg sgcafefood     25          0.206127
11                   per person photo     33          0.206084
4                    per person photo     33          0.206084
19                        xiao ya tou     32          0.203905
3                         xiao ya tou     32          0.203905
8   cafehoppingsg sgcafefood sgfoodie     26          0.198199
14  sgcafefood sgfoodie singaporeeats     26          0.198199
4   cafehoppingsg sgcafefood sgfoodie     26          0.198199
13                       sweet potato     60          0.188713
..                                ...    ...               ...
14                      raffles place     47          0.159880
6                       thai milk tea     24          0.149468
16                      thai milk tea     24          0.149468
14                     15 duxton road     22          0.149094
0                      15 duxton road     22          0.149094
12              duxton road singapore     24          0.145213
6               duxton road singapore     24          0.145213
10                     road singapore     72          0.139507
12                     road singapore     72          0.139507
13                         salted egg     92          0.135809
1                          salted egg     92          0.135809
8            http danielfooddiary com     20          0.132154
7                          flat white     74          0.132035
3                          flat white     74          0.132035
4                           earl grey     73          0.130763
2                           earl grey     73          0.130763
12                       black sesame     45          0.129306
0                        black sesame     45          0.129306
9                          pork belly     46          0.129277
1                       6 duxton hill     24          0.126393
11                      6 duxton hill     24          0.126393
5               duxton hill singapore     23          0.121452
13              duxton hill singapore     23          0.121452
10                neil road singapore     23          0.120581
1                     salted egg yolk     24          0.104435
13                    salted egg yolk     24          0.104435
1                           cold brew     45          0.011630
18               www misstamchiak com     20          0.006757
7           hill singapore 089592\r\n      0          0.000000
5                       fried chicken     44         -0.034049

[70 rows x 3 columns]